# airfoil_config.yaml
camber_line:
  control_points_params:
    P1_k_factor: 0.4
    P2_x: 0.5
    P2_y: 0.05
    P3_k_factor: -0.25
  inlet_angle_deg: 45
  outlet_angle_deg: -50
  stagger_angle_deg: -25

top_thickness:
  control_points_params:
    P1_k_factor: 0.2
    P2_x: 0.1
    P2_y: 0.03
    P3_k_factor: 0
  inlet_angle_deg: 40
  outlet_angle_deg: -0
  le_y_thickness: 0.02 # Y-coordinate of P0 for thickness curve (half-thickness at LE)
  p4_y: 0.01           # Y-coordinate of P4 for thickness curve (half-thickness at TE)

bottom_thickness:
  control_points_params:
    P1_k_factor: 0.2
    P2_x: 0.1
    P2_y: 0.03
    P3_k_factor: 0
  inlet_angle_deg: 40
  outlet_angle_deg: -0
  le_y_thickness: 0.02 # Y-coordinate of P0 for thickness curve (half-thickness at LE)
  p4_y: 0.01           # Y-coordinate of P4 for thickness curve (half-thickness at TE)

output_settings:
  output_airfoil_filename: None #"generated_airfoil.dat"
  output_camber_filename: None #"generated_camber_line.txt"
  output_top_thickness_filename: None #"generated_top_thickness.txt"
  output_bottom_thickness_filename: None #"generated_bottom_thickness.txt"
  plot_title: "Generated Airfoil Shape"
  num_points_on_curve: 1000 # Number of points for main Bezier curves
  num_points_on_arc: 50    # Number of points for LE/TE arcs
  chord_length_for_export: 50.0 # Desired chord length when exporting to .dat

